name: netflix_clone_court
description: "Netflix Clone Movie Discovery App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  flutter_bloc: ^9.1.1
  google_fonts: ^8.2.1
  dio: ^5.7.0
  get_it: ^8.0.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  equatable: ^2.0.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
